spring:
  config:
    activate:
      on-profile: test
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace  # query? ?? ?? ?? ????? ??? ? ?? ?????.